// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU42o6FP9ANyhP07HCK2Zavu39SnV0bts',
    appId: '1:1084599200097:web:cef90b5c06f162a14abd20',
    messagingSenderId: '1084599200097',
    projectId: 'sih-fit-test',
    authDomain: 'sih-fit-test.firebaseapp.com',
    storageBucket: 'sih-fit-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuLSjNFhGgO0nNUxugCwrirBEURC4TazE',
    appId: '1:1084599200097:android:8c4fe12976a1ead74abd20',
    messagingSenderId: '1084599200097',
    projectId: 'sih-fit-test',
    storageBucket: 'sih-fit-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDARRv13wCMicj1K5wXv1W2i_NXKPbLMTQ',
    appId: '1:1084599200097:ios:213a327bb824e7cd4abd20',
    messagingSenderId: '1084599200097',
    projectId: 'sih-fit-test',
    storageBucket: 'sih-fit-test.appspot.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
